### ISSUE TITLE
AvroSchemaGenerator should support generation of "fixed" field-types

### ISSUE THREAD

**Issue by joshng** [FasterXML/jackson-dataformat-avro#15]
Values whose byte-lengths are constant are more efficiently to packed in avro as "fixed" fields, because this encoding saves the overhead of a length-prefix. UUIDs and MD5/SHA hashes are common examples where this encoding can be beneficial.

The AvroSchemaGenerator does not currently support this field-type; it just treats byte[]/ByteBuffer fields as length-prefixed "bytes" fields.

Supporting "fixed" will likely involve some sort of annotation in the POJO to specify both the length and "name" of the generated datatype (note that "name" is currently required, for some reason, for every fixed type).

**Comment by bkenned4** [comment]
This looks to be fixed with commit 5251e2a4a79694fde5f273e886d95952202bcadb.  Can this be closed?

**Comment by cowtowncoder** [comment]
Sounds good, will do.
