### ISSUE TITLE
Add AVRO_BUFFERING feature (enabled by default/existing behavior)

### ISSUE THREAD

**Issue by oakad** [FasterXML/jackson-dataformat-avro#21]
From the looking at AvroSchema class, I gather that the avro encoder/decoder is always obtained through call to "binaryEncoder()"/"binaryDecoder()" factory methods which returns buffered coders.

In many cases the buffering behavior of default AVRO coders is strongly undesirable. In particular, in many cases avro data may be followed by non-avro data in the underlying protocol (such as HTTP multipart/form-data) and thus the decoder must not advance the input stream more than absolutely necessary per schema definitions. When encoders are concerned , buffering may be outright redundant, as underlying output stream may already be buffered by down the line processor.

Avro library provides a non-buffering implementation of its coders ("directBinaryEncoder()"/"directBinaryDecoder()") for this exact use case. Can the jackson avro format handler be updated to enable use of those direct coders (per configuration setting or somehow else)?

**Comment by cowtowncoder** [comment]
We are open to suggestion on improvements, for example in form of Pull requests.

One possible way to support this would be to add new `AvroParser.Feature` and `AvroGenerator.Feature` constants, and use those to determine which encoder/decoder to construct.
That should be quite easy to do.
