### ISSUE TITLE
Similar to issue #6, MapWriteContext.createChildObjectContext() should call _schema.getValueType()

### ISSUE THREAD

**Issue by shoeree** [FasterXML/jackson-dataformat-avro#23]
Hello!

I was attempting to serialize an Avro record containing a "map" with record-type values, and encountered this error:

```JsonMappingException: Not an array: <redacted>```

... I see that in Issue #6, deserializing the "map" type appears to call ```getElementType()```. In MapWriteContext.java, ```getElementType()``` is also called, like so:

```java
@Override
public final AvroWriteContext createChildObjectContext() throws JsonMappingException
{
    _verifyValueWrite();
    AvroWriteContext child = _createObjectContext(_schema.getElementType());
    _data.put(_currentName, child.rawValue());
    return child;
}
```

Shouldn't this instead use ```_schema.getValueType()```?

**Comment by cowtowncoder** [comment]
Yes, quite probably it should.

Any possibility of a simple unit test? :)
