### ISSUE TITLE
Should indicate type that was requested when complaining about Any not being supported

### ISSUE THREAD

**Issue by osi** [FasterXML/jackson-dataformat-avro#26]
in https://github.com/FasterXML/jackson-dataformat-avro/blob/master/src/main/java/com/fasterxml/jackson/dataformat/avro/schema/VisitorFormatWrapperImpl.java#L151

the exception being thrown for expectAnyFormat should include the passed in convertedType in the error message

**Comment by cowtowncoder** [comment]
@osi Do you have bit more info to share wrt error message here and what could be more useful version (just an idea of how to add, can be improved). I'll dig into code when I get a chance, but it's easier to glance through issues when prioritizing, help decide which are easy to fix/improve.

**Comment by osi** [comment]
Just have it be something like:

```java
    @Override
    public JsonAnyFormatVisitor expectAnyFormat(JavaType convertedType) {
        // could theoretically create union of all possible types but...
        return _throwUnsupported("'Any' type not supported when trying to expect " + convertedType);
    }
```

(I discovered this when convertedType was an OptionalDouble)
