### ISSUE TITLE
Primitive fields inside unwrapped optional value not considered nullable in schema

### ISSUE THREAD

**Issue by osi** [FasterXML/jackson-dataformat-avro#29]
When generating an avro schema, given:

```java
class A {
 @JsonUnwrapped
 public final Optional<B> b;
}

class B {
  public final boolean flag;
}
```

The generated schema for A does not consider the 'flag' field to be nullable.

**Comment by cowtowncoder** [comment]
Sounds like this might be a more general databind issue, wrt passing type information for schema generation. With new "reference type" (added in 2.6) it should actually be possible to handle this in generic fashion. Either way, should be fixed, as much as I hate having to add all these work arounds for `Optional`.

**Comment by cowtowncoder** [comment]
Hmmh. Would be great to have a test case, but just realized that it may not be trivially easy to support this, since it would require transitivity via unwrapped and optional wrappings.

**Comment by cowtowncoder** [comment]
Moved to https://github.com/FasterXML/jackson-dataformats-binary/issues/12
