### ISSUE TITLE
Follow up to https://github.com/FasterXML/jackson-dataformat-avro/issues/30

### ISSUE THREAD

**Issue by jmoney8080** [FasterXML/jackson-dataformat-avro#31]
I don't know if this is the preferred way of asking a follow up, but i couldn't reopen https://github.com/FasterXML/jackson-dataformat-avro/issues/30

Turns out, my use case is I have a setter AND getter but they map to a different physical field and there is no logical field.  How would I go about filtering out logical fields to only physical fields?

I thought about implementing a PropertyFilter but having a hard time figuring out how to plug this in and even what the PropertyFilter should do…

**Comment by cowtowncoder** [comment]
I hope you saw my answer on #30; visibility checker settings FTW.
For follow-up questions, `jackson-user` works wonders!
