### ISSUE TITLE
(2.8) default value not supported

### ISSUE THREAD

**Issue by turbospaces** [FasterXML/jackson-dataformat-avro#34]
Right now RecordVisitor create Fields without default VALUE, which causes problem when the schema evaluates and client operates with OLD data http://ben-tech.blogspot.com/2013/05/avro-schema-evolution.html

I suggest to change Record visitor to:
```java
@Override
public void optionalProperty(BeanProperty writer) throws JsonMappingException {
  Schema schema = schemaForWriter( writer );
  if ( !writer.getType().isPrimitive() ) {
      schema = AvroSchemaHelper.unionWithNull( schema );
  }
    _fields.add( new Schema.Field( writer.getName(), schema, null,
       writer.isRequired() ? null : Schema.parseJson( "null" ) ) );
}
```

**Comment by cowtowncoder** [comment]
I am not against this, although in a way it would be nice to have some way to indicate need for default values.

Due to potential backwards compatibility concerns I think it is safest to add this in 2.8.

**Comment by turbospaces** [comment]
any plans to add support for default values? when this can be implemented?

**Comment by cowtowncoder** [comment]
@turbospaces I haven't had time to work on this. To get code changed, a unit test would be needed to show problem being solved; a PR would be great.

**Comment by cowtowncoder** [comment]
Moved to https://github.com/FasterXML/jackson-dataformats-binary/issues/13
