### ISSUE TITLE
Could not crate .avro file

### ISSUE THREAD

**Issue by srini-daruna** [FasterXML/jackson-dataformat-avro#42]
Hi, 

I created avro schema from class and got the byte array and want to write the data to avro file. 
How can i do that.?

**Comment by dsyer** [comment]
The internet is full of utilities to copy a byte array to a file (e.g. look at Apache commons-io `FileUtils`, and Spring also has one).

**Comment by srini-daruna** [comment]
If i have written the byte array to file and used spark-avro or avro-tools, it is not recognizing the file as avro. I have used same schema and byte array from jackson. Probably, i might have not pointed my question in right direction..

**Comment by dsyer** [comment]
Probably. Maybe you could share some code, and explain what you were trying to do in more detail?

**Comment by cowtowncoder** [comment]
@srini-daruna For better or worse, Avro dictates different format for files than network transport -- Avro files are supposed to have both prefix and pre-written schema as JSON. Currently this module only does "raw" encoded content, and does not have means to add wrapper stuff.
Addition of header and avro schema would be a good addition I think.

**Comment by cowtowncoder** [comment]
Moved to https://github.com/FasterXML/jackson-dataformats-binary/issues/15
