### ISSUE TITLE
@AvroMeta support

### ISSUE THREAD

**Issue by jvmlet** [FasterXML/jackson-dataformat-avro#43]
Hello
What is the `@AvroMeta` abstraction API to include custom property into schema when using `AvroMapper` ? 
`@AvroMeta` is not annotated with `@Repeatable`, so it would be great to have multiple properties on field/class.
Thanks

**Comment by cowtowncoder** [comment]
Please use mailing list for usage questions:

https://groups.google.com/forum/#!forum/jackson-user
